name: Build Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.*'
      - 'src/**'

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build x86
        run: cargo build --release --locked --target x86_64-unknown-linux-gnu

  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cross
        run: cargo install cross@0.2.5
      - name: Build arm
        run: cross build --release --locked --target aarch64-unknown-linux-gnu 