name: Build Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.*'
      - 'src/**'

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build x86
        run: cargo build --release --locked --target x86_64-unknown-linux-gnu

  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build ARM
        uses: cross-rs/cross@v0.2.5
        with:
          args: build --target x86_64-unknown-linux-gnu --release