name: Build Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.*'
      - 'src/**'

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: build
        name: Build x86 binary
        uses: ./.github/actions/build-with-cross
        with:
          target: x86_64-unknown-linux-gnu

  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: build
        name: Build ARM binary
        uses: ./.github/actions/build-with-cross
        with:
          target: aarch64-unknown-linux-gnu