name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag_exists: ${{ steps.tag_check.outputs.exists }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep -m1 -E '^\s*version\s*=' Cargo.toml | sed -E 's/^\s*version\s*=\s*"([^"]+)".*/\1/')
          if [ -z "$VERSION" ]; then
            echo "::error::Could not read version from Cargo.toml"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_check
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/v${{ steps.get_version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"

      - name: Create GitHub Release
        id: create_release
        if: steps.tag_check.outputs.exists == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-x86:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tag_exists == 'false'
    steps:
      - name: Build x86 binary
        id: build
        uses: ./.github/actions/build-with-cross
        with:
          target: x86_64-unknown-linux-gnu

      - name: Upload x86 binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.binary-path }}
          asset_name: guilt-x86_64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-arm:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tag_exists == 'false'
    steps:
      - name: Build x86 binary
        id: build
        uses: ./.github/actions/build-with-cross
        with:
          target: x86_64-unknown-linux-gnu

      - name: Upload x86 binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.binary-path }}
          asset_name: guilt-x86_64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}